#!/usr/bin/env python3
"""Regression checks for the Thanh Tra deterministic pre-scan engine."""

from __future__ import annotations

import json
import importlib.util
import subprocess
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PRE_SCAN = ROOT / "skills" / "thanhtra" / "scripts" / "thanhtra-pre-scan.py"
THANHTRA_CLI = ROOT / "bin" / "thanhtra"


def load_pre_scan_module():
    sys.dont_write_bytecode = True
    spec = importlib.util.spec_from_file_location("thanhtra_core_prescan", ROOT / "thanhtra" / "core" / "prescan.py")
    if spec is None or spec.loader is None:
        raise RuntimeError("cannot load pre-scan module")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def run(cmd: list[str], cwd: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, cwd=cwd, text=True, capture_output=True, check=True)


def build_fixture(root: Path) -> None:
    (root / "app.py").write_text(
        """
import os
import subprocess

API_TOKEN = "FAKE_TOKEN_VALUE_1234567890ABCDE"

def ping(host):
    return subprocess.run(f"ping -c 1 {host}", shell=True, capture_output=True)
""".strip()
        + "\n",
        encoding="utf-8",
    )
    (root / "requirements.txt").write_text("flask==2.0.0\n", encoding="utf-8")
    (root / "Cargo.toml").write_text(
        """
[package]
name = "thanhtra-fixture"
version = "0.1.0"
edition = "2021"
""".lstrip(),
        encoding="utf-8",
    )
    (root / "Cargo.lock").write_text(
        """
# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "thanhtra-fixture"
version = "0.1.0"
""".lstrip(),
        encoding="utf-8",
    )
    (root / "docker-compose.yml").write_text(
        """
services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
""".lstrip(),
        encoding="utf-8",
    )
    run(["git", "init"], root)
    run(["git", "add", "."], root)
    run(["git", "commit", "-m", "fixture with token cleanup signal"], root)
    # Untracked file: vibe code thường chưa commit, pre-scan vẫn phải thấy.
    (root / "TODO.md").write_text("- [ ] ship it\n", encoding="utf-8")
    # Artifact của chính tool: scan lại sẽ tạo feedback loop — phải bị loại.
    (root / ".thanhtra-pre-scan.json").write_text('{"schema": "stale"}\n', encoding="utf-8")
    (root / "thanhtra-reports").mkdir()
    (root / "thanhtra-reports" / "scan-old.md").write_text("# old report\n", encoding="utf-8")


def assert_true(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def validate_parsers() -> None:
    module = load_pre_scan_module()
    npm_sample = json.dumps({
        "vulnerabilities": {
            "lodash": {
                "severity": "high",
                "range": "<=4.17.20",
                "via": [{"source": 1106913, "title": "Command Injection"}],
                "fixAvailable": True,
            }
        }
    })
    cargo_sample = json.dumps({
        "vulnerabilities": {"list": []},
        "warnings": {
            "unmaintained": [{
                "package": {"name": "paste", "version": "1.0.15"},
                "advisory": {
                    "id": "RUSTSEC-2024-0436",
                    "package": "paste",
                    "title": "paste - no longer maintained",
                    "url": "https://github.com/dtolnay/paste",
                },
            }]
        },
    })
    pip_sample = """
Name  Version ID             Fix Versions
----- ------- -------------- ------------
flask 0.12.2  PYSEC-2019-179 1.0
""".strip()

    assert_true(module.parse_npm_audit(npm_sample)[0]["package"] == "lodash", "npm audit parser failed")
    assert_true(module.parse_pip_audit(pip_sample)[0]["advisory"] == "PYSEC-2019-179", "pip-audit parser failed")
    assert_true(module.parse_cargo_audit_warnings(cargo_sample)[0]["package"] == "paste", "cargo warning parser failed")


def main() -> int:
    validate_parsers()
    with tempfile.TemporaryDirectory(prefix="thanhtra-pre-scan-") as tmp:
        # Fixture nằm trong subdir để output/evidence không lọt vào file_count.
        fixture = Path(tmp) / "repo"
        fixture.mkdir()
        build_fixture(fixture)
        out = Path(tmp) / "evidence.json"
        run(["python3", str(PRE_SCAN), "--root", str(fixture), "--no-audit", "--output", str(out)], ROOT)
        data = json.loads(out.read_text(encoding="utf-8"))
        cli = run([str(THANHTRA_CLI), "scan", str(fixture), "--json", "--no-audit"], ROOT)
        cli_prescan = run([str(THANHTRA_CLI), "prescan", "--root", str(fixture), "--no-audit"], ROOT)
        cli_data = json.loads(cli.stdout)
        cli_prescan_data = json.loads(cli_prescan.stdout)

    assert_true(data["schema"] == "thanhtra-pre-scan/v1", "schema mismatch")
    assert_true(data["is_git_repo"] is True, "git repo not detected")
    assert_true(
        data["file_count"] == 6,
        "unexpected file count (5 tracked + 1 untracked; tool artifacts excluded)",
    )
    assert_true(data["file_kind_counts"].get("dependency") == 3, "dependency file kind count missing")
    assert_true(data["hotspot_file_count"] == 1, "hotspot candidate file count mismatch")
    assert_true(data["language_counts"].get("python") == 1, "python language count missing")
    assert_true(data["dependency_files"] == ["Cargo.lock", "Cargo.toml", "requirements.txt"], "dependency file not detected")
    assert_true("cargo-audit" in data["tool_availability"], "cargo-audit availability missing")
    assert_true(data["secret_hits_masked"], "masked secret hit missing")
    assert_true(data["docker_exposures"], "docker exposure missing")
    assert_true(data["hotspots_by_rule"].get("COMMAND-INJECTION"), "command injection hotspot missing")
    assert_true(len(data["fingerprint_sha256"]) == 64, "fingerprint missing")
    assert_true(data["dependency_audits"] == [], "no-audit should skip dependency audits")
    assert_true(data["dependency_warnings"] == [], "no-audit should skip dependency warnings")
    assert_true(data["audit_gaps"] == [], "no-audit should not emit audit gaps")
    assert_true(cli_data["schema"] == "thanhtra-scan/v1", "CLI schema mismatch")
    assert_true(cli_data["summary"]["file_count"] == 6, "CLI file count mismatch")
    assert_true(cli_data["summary"]["dependency_vulnerability_count"] == 0, "CLI no-audit dependency count mismatch")
    assert_true(cli_data["evidence"]["fingerprint_sha256"] == data["fingerprint_sha256"], "CLI evidence mismatch")
    assert_true(cli_prescan_data["schema"] == "thanhtra-pre-scan/v1", "CLI prescan schema mismatch")
    assert_true(cli_prescan_data["fingerprint_sha256"] == data["fingerprint_sha256"], "CLI prescan evidence mismatch")

    validate_triage_build(data)

    print("Pre-scan validation passed.")
    return 0


def validate_triage_build(evidence: dict) -> None:
    """Triage request/schema must build correctly offline (no network/API key)."""
    spec = importlib.util.spec_from_file_location(
        "thanhtra_core_triage", ROOT / "thanhtra" / "core" / "triage.py"
    )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    assert_true(len(module.ALL_RULES) == 22, "triage should know 22 rules")
    assert_true(module.CRITICAL_RULES <= set(module.ALL_RULES), "critical rules must be a subset")
    assert_true("PROMPT-INJECTION" in module.ALL_RULES, "rule #22 missing from triage")
    json.dumps(module.TRIAGE_SCHEMA)  # schema must be JSON-serializable

    body = module.build_request_body(evidence, module.DEFAULT_MODEL)
    assert_true(body["model"] == "claude-opus-4-8", "triage default model mismatch")
    assert_true(body["thinking"] == {"type": "adaptive"}, "triage must use adaptive thinking")
    assert_true(
        body["output_config"]["format"]["type"] == "json_schema",
        "triage must request structured output",
    )
    assert_true("hotspots_by_rule" in body["messages"][0]["content"], "triage must send evidence")

    ob = module.build_openai_body(evidence, "test-model", structured=True)
    assert_true(ob["messages"][0]["role"] == "system", "openai body needs system message")
    assert_true(
        ob["response_format"]["json_schema"]["strict"] is True,
        "openai structured body must request strict json_schema",
    )
    od = module.build_openai_body(evidence, "test-model", structured=False)
    assert_true(od["response_format"] == {"type": "json_object"}, "openai fallback shape mismatch")
    assert_true(module._loads_lenient('```json\n{"x":1}\n```') == {"x": 1}, "lenient JSON parse failed")


if __name__ == "__main__":
    raise SystemExit(main())
